Feat/gameboard
amunds1/LetterLink pull request #217
Opened 2023-01-13 20:34 UTC by kristinelarssen

- Centered elements in the game board
- Squared game board cells
- Made buttons green/disabled
- Improvements in displaying the points

2023-01-15 14:51 UTC, amunds1 commented on components/game/Points.tsx
> +  }
Nice! Foreslår derimot at vi lagrer totalpoeng også i Firebase, så slipper vi å kjøre denne snutten hver gang

2023-01-15 15:04 UTC, amunds1 requested changes
Bra jobba! La igjen noen kommentarer

2023-01-15 15:04 UTC, amunds1 commented on components/game/Points.tsx
> +  }
Totalpoeng kan kanskje lagres på rotnivå av _game-dokumentet_. Da slipper vi å hente motstanderen sitt brett.

2023-01-16 09:15 UTC, kristinelarssen commented on pages/api/utils/newCheckRowOrColumn.ts
> -    }
Slik jeg forstå det under når jeg testet frem og tilbake, så virket det ikke som den hadde noe betydning i det hele tatt. Men gjerne ta å se over det!

2023-01-16 09:17 UTC, kristinelarssen commented on components/game/Points.tsx
> +  }
Ja godt poeng!

2023-01-16 09:21 UTC, kristinelarssen commented on components/game/Points.tsx
> +  }, [gameContext?.userUID, gameContext?.opponentID])
Det høres ut som en glimrende ide!

2023-01-24 12:51 UTC, merged